name: Build

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - 'main'
      - 'master'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Package app
      uses: actions/upload-artifact@v4
      with:
        name: check-digit
        path: |
          dist/

    - name: Save package
      uses: actions/download-artifact@v4
      with:
        name: check-digit
        path: |
          dist
          
    - name: Change directory to dist
      run: cd ./dist
      
    - name: Publish application
      uses: deka0106/upload-to-dropbox@v2
      with:
        dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        src: /**/*
        dest: /
        mode: overwrite
        multiple: true
